In [176]:
import numpy as np
print('Examen')

Examen


In [177]:
print('2) Crear un vector de ceros de tamaño 10')

2) Crear un vector de ceros de tamaño 10


In [178]:
vector_zeros_10= np.zeros(10)
vector_zeros_10

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [179]:
print('3) Crear un vector de ceros de tamaño 10 y el de la posicion 5 sea igual a 1')

3) Crear un vector de ceros de tamaño 10 y el de la posicion 5 sea igual a 1


In [180]:
vector_zeros_10_1= np.zeros(10)
vector_zeros_10_1[5] =1
vector_zeros_10_1

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [181]:
## 4) Cambiar el orden de un vector de 50 elementos, el de la posicion 1 es el de la 50 etc.

In [182]:
vector_50_invertido = np.arange(50,0,-1)
vector_50_invertido

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [183]:
## 5) Crear una matriz de 3 x 3 con valores del cero al 8

In [184]:
matriz_3_3 = np.arange(0,9).reshape(3,3)
matriz_3_3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [185]:
## 6) Encontrar los indices que no sean cero en un arreglo

In [186]:
arreglo = [1,2,0,0,4,0]

In [187]:
arreglo_np = np.nonzero(arreglo)
print(arreglo_np[0])

[0 1 4]


In [188]:
## 7) Crear una matriz de identidad 3 x 3 

In [189]:
matriz_zeros_33 = np.identity(3)
matriz_zeros_33

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [190]:
## 8) Crear una matriz 3 x 3 x 3 con valores randomicos

In [191]:
matriz_ones_27 = np.random.rand(3,3,3)
matriz_ones_27

array([[[0.38633537, 0.82504846, 0.51356567],
        [0.61093605, 0.02656852, 0.49756029],
        [0.0338338 , 0.53289654, 0.34653026]],

       [[0.31018531, 0.84129447, 0.20358812],
        [0.5714918 , 0.50477661, 0.42077698],
        [0.22029089, 0.66163915, 0.07423641]],

       [[0.0297266 , 0.09878984, 0.36541467],
        [0.18221229, 0.74730477, 0.83146476],
        [0.81429274, 0.83118925, 0.22765262]]])

In [192]:
## 9) Crear una matriz 10 x 10 y encontrar el mayor y el menor

In [193]:
matriz_10_10 = np.random.rand(10,10)
matriz_10_10
print(f'Mayor: {matriz_10_10.max()}')
print(f'Menor: {matriz_10_10.min()}')

Mayor: 0.9829226103987928
Menor: 0.014813183419181808


In [194]:
from PIL import Image
im = Image.open('logo.jpg')
logo = np.array(im)

In [195]:
#11) ¿Como crear una serie de una lista, diccionario o arreglo?

In [196]:
import pandas as pd
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

In [197]:
serie_lista = pd.Series(mylist)
serie_lista

0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object

In [198]:
serie_arr = pd.Series(myarr)
serie_arr

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
21    21
22    22
23    23
24    24
25    25
dtype: int32

In [199]:
serie_dict = pd.Series(mydict)
serie_dict

a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64

In [200]:
## 12) ¿Como convertir el indice de una serie en una columna de un DataFrame?

In [201]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)
ser

a     0
b     1
c     2
e     3
d     4
f     5
g     6
h     7
i     8
j     9
k    10
l    11
m    12
n    13
o    14
p    15
q    16
r    17
s    18
t    19
u    20
v    21
w    22
x    23
y    24
z    25
dtype: int64

In [202]:
# Transformar la serie en dataframe y hacer una columna indice
df = pd.DataFrame(ser.index)
df

0
0   a
1   b
2   c
3   e
4   d
5   f
6   g
7   h
8   i
9   j
10  k
11  l
12  m
13  n
14  o
15  p
16  q
17  r
18  s
19  t
20  u
21  v
22  w
23  x
24  y
25  z

In [203]:
## 13) ¿Como combinar varias series para hacer un DataFrame?

In [204]:
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))
print(ser1)
print(ser2)

0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
15    15
16    16
17    17
18    18
19    19
20    20
21    21
22    22
23    23
24    24
25    25
dtype: int32


In [205]:
series_com = pd.DataFrame([ser1,ser2])
series_com  

0  1  2  3  4  5  6  7  8  9  ...  16  17  18  19  20  21  22  23  24  25
0  a  b  c  e  d  f  g  h  i  j ...   q   r   s   t   u   v   w   x   y   z
1  0  1  2  3  4  5  6  7  8  9 ...  16  17  18  19  20  21  22  23  24  25

[2 rows x 26 columns]

In [206]:
## 14) ¿Como obtener los items que esten en una serie A y no en una serie B?

In [215]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
ser1.where(ser1 == ser2)

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
dtype: float64

In [212]:
## 16) ¿Como obtener el numero de veces que se repite un valor en una serie?

In [225]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
print(type(ser))
ser.value_counts()

<class 'pandas.core.series.Series'>


a    7
h    5
c    4
f    4
d    3
e    3
b    2
g    2
dtype: int64

In [226]:
## 18) ¿Como transformar una serie de un arreglo de numpy a un DataFrame con un `shape` definido?

In [235]:
## 22)¿Como importar solo columnas especificas de un archivo csv?

In [236]:
CSV_PATH = "C:\\Users\\rprado\\2018-b-gr1-master\\prado-roberto-examen-1bim\\BostonHousing.csv"

In [239]:
music_dataset = pd.read_csv(CSV_PATH, usecols=['crim'])
print(music_dataset.shape)

(506, 1)
